// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260523154011_SeedMockData")]
    partial class SeedMockData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("dotnet_store.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("dotnet_store.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("dotnet_store.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CartId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("dotnet_store.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("UrunId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("dotnet_store.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KategoriAdi = "Telefon",
                            Url = "telefon"
                        },
                        new
                        {
                            Id = 2,
                            KategoriAdi = "Bilgisayar",
                            Url = "bilgisayar"
                        },
                        new
                        {
                            Id = 3,
                            KategoriAdi = "Tablet",
                            Url = "tablet"
                        },
                        new
                        {
                            Id = 4,
                            KategoriAdi = "Erkek Giyim",
                            Url = "erkek-giyim"
                        },
                        new
                        {
                            Id = 5,
                            KategoriAdi = "Kadın Giyim",
                            Url = "kadin-giyim"
                        },
                        new
                        {
                            Id = 6,
                            KategoriAdi = "Ayakkabı",
                            Url = "ayakkabi"
                        },
                        new
                        {
                            Id = 7,
                            KategoriAdi = "Saat",
                            Url = "saat"
                        },
                        new
                        {
                            Id = 8,
                            KategoriAdi = "Parfüm & Kozmetik",
                            Url = "parfum-kozmetik"
                        },
                        new
                        {
                            Id = 9,
                            KategoriAdi = "Aksesuar",
                            Url = "aksesuar"
                        },
                        new
                        {
                            Id = 10,
                            KategoriAdi = "Ev & Mobilya",
                            Url = "ev-mobilya"
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresSatiri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostaKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiparisNotu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ToplamFiyat")
                        .HasColumnType("float");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("dotnet_store.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Fiyat")
                        .HasColumnType("float");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UrunId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("dotnet_store.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliderlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Slider 1 Açıklama",
                            Aktif = true,
                            Baslik = "Slider 1 Başlık",
                            Index = 0,
                            Resim = "slider-1.jpeg"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Slider 2 Açıklama",
                            Aktif = true,
                            Baslik = "Slider 2 Başlık",
                            Index = 1,
                            Resim = "slider-2.jpeg"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Slider 3 Açıklama",
                            Aktif = true,
                            Baslik = "Slider 3 Başlık",
                            Index = 2,
                            Resim = "slider-3.jpeg"
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<bool>("Anasayfa")
                        .HasColumnType("bit");

                    b.Property<double>("Fiyat")
                        .HasColumnType("float");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Apple iPhone 13 Pro, A15 Bionic çip, ProMotion 120Hz Super Retina XDR ekran ve üçlü kamera sistemi.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 36300.0,
                            KategoriId = 1,
                            Resim = "iphone-13-pro.webp",
                            UrunAdi = "iPhone 13 Pro"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Apple iPhone X, OLED Super Retina ekran, Face ID ve çift arka kamera ile klasik bir model.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 29700.0,
                            KategoriId = 1,
                            Resim = "iphone-x.webp",
                            UrunAdi = "iPhone X"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Samsung Galaxy S10, Dynamic AMOLED ekran, üçlü kamera ve kablosuz ters şarj özelliği.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 23100.0,
                            KategoriId = 1,
                            Resim = "samsung-galaxy-s10.webp",
                            UrunAdi = "Samsung Galaxy S10"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Samsung Galaxy S8, kavisli Infinity Display ve IP68 su geçirmezlik standardı.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 16500.0,
                            KategoriId = 1,
                            Resim = "samsung-galaxy-s8.webp",
                            UrunAdi = "Samsung Galaxy S8"
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Oppo F19 Pro Plus 5G, AMOLED ekran ve 65W SuperVOOC 2.0 hızlı şarj.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 13200.0,
                            KategoriId = 1,
                            Resim = "oppo-f19-pro-plus.webp",
                            UrunAdi = "Oppo F19 Pro Plus"
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Apple MacBook Pro 14 inç, M serisi çip, Liquid Retina XDR ekran ve uzun pil ömrü.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 66000.0,
                            KategoriId = 2,
                            Resim = "macbook-pro-14.webp",
                            UrunAdi = "MacBook Pro 14\" Space Grey"
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Asus Zenbook Pro çift ekranlı dizüstü, OLED ekran ve içerik üreticileri için tasarım.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 59400.0,
                            KategoriId = 2,
                            Resim = "asus-zenbook-pro.webp",
                            UrunAdi = "Asus Zenbook Pro Duo"
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "Huawei MateBook X Pro, 3K dokunmatik ekran, ince magnezyum kasa ve uzun pil ömrü.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 46200.0,
                            KategoriId = 2,
                            Resim = "huawei-matebook-x-pro.webp",
                            UrunAdi = "Huawei MateBook X Pro"
                        },
                        new
                        {
                            Id = 9,
                            Aciklama = "Dell XPS 13 9300, InfinityEdge 4K ekran ve Intel Core i7 işlemci.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 49500.0,
                            KategoriId = 2,
                            Resim = "dell-xps-13.webp",
                            UrunAdi = "Dell XPS 13 9300"
                        },
                        new
                        {
                            Id = 10,
                            Aciklama = "Lenovo Yoga 920 2-in-1 dönüştürülebilir dizüstü, dokunmatik ekran ve Active Pen desteği.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 36300.0,
                            KategoriId = 2,
                            Resim = "lenovo-yoga-920.webp",
                            UrunAdi = "Lenovo Yoga 920"
                        },
                        new
                        {
                            Id = 11,
                            Aciklama = "Apple iPad Mini 2021, A15 Bionic çip, 8.3 inç Liquid Retina ekran ve Apple Pencil 2 desteği.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 16500.0,
                            KategoriId = 3,
                            Resim = "ipad-mini-2021.webp",
                            UrunAdi = "iPad Mini 2021 Starlight"
                        },
                        new
                        {
                            Id = 12,
                            Aciklama = "Samsung Galaxy Tab S8+, 12.4 inç Super AMOLED ekran ve S Pen ile profesyonel kullanım.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 19800.0,
                            KategoriId = 3,
                            Resim = "galaxy-tab-s8-plus.webp",
                            UrunAdi = "Galaxy Tab S8+ Grey"
                        },
                        new
                        {
                            Id = 13,
                            Aciklama = "Samsung Galaxy Tab, geniş ekran ve uzun pil ömrü ile günlük kullanım için ideal tablet.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 11500.0,
                            KategoriId = 3,
                            Resim = "galaxy-tab-white.webp",
                            UrunAdi = "Galaxy Tab"
                        },
                        new
                        {
                            Id = 14,
                            Aciklama = "Pamuklu, regular fit mavi ve siyah kareli erkek gömlek — günlük şıklık.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 990.0,
                            KategoriId = 4,
                            Resim = "mavi-siyah-kareli-gomlek.webp",
                            UrunAdi = "Mavi & Siyah Kareli Gömlek"
                        },
                        new
                        {
                            Id = 15,
                            Aciklama = "Klasik ekose desenli uzun kollu erkek gömlek, slim fit kalıp.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 1155.0,
                            KategoriId = 4,
                            Resim = "ekoseli-gomlek.webp",
                            UrunAdi = "Ekoseli Erkek Gömlek"
                        },
                        new
                        {
                            Id = 16,
                            Aciklama = "Yaz aylarında konforlu kullanım için pamuklu kısa kollu erkek gömlek.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 660.0,
                            KategoriId = 4,
                            Resim = "kisa-kollu-gomlek.webp",
                            UrunAdi = "Kısa Kollu Erkek Gömlek"
                        },
                        new
                        {
                            Id = 17,
                            Aciklama = "Klasik kareli desen, regular fit erkek gömlek — ofis ve sosyal etkinlikler için.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 924.0,
                            KategoriId = 4,
                            Resim = "kareli-erkek-gomlek.webp",
                            UrunAdi = "Kareli Erkek Gömlek"
                        },
                        new
                        {
                            Id = 18,
                            Aciklama = "Gigabyte Aorus baskılı pamuklu gaming tişört, oyun severler için.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 825.0,
                            KategoriId = 4,
                            Resim = "aorus-tisort.webp",
                            UrunAdi = "Aorus Gaming Tişört"
                        },
                        new
                        {
                            Id = 19,
                            Aciklama = "Şık tasarımlı siyah uzun gece elbisesi — özel davetler ve gece etkinlikleri için.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 4290.0,
                            KategoriId = 5,
                            Resim = "siyah-gece-elbisesi.webp",
                            UrunAdi = "Siyah Uzun Gece Elbisesi"
                        },
                        new
                        {
                            Id = 20,
                            Aciklama = "Deri korse ve uyumlu etek takımı — modern ve iddialı bir görünüm.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 2970.0,
                            KategoriId = 5,
                            Resim = "deri-korse-etek.webp",
                            UrunAdi = "Deri Korse ve Etek Takım"
                        },
                        new
                        {
                            Id = 21,
                            Aciklama = "Marni tasarım kırmızı ve siyah iki parça takım, premium kumaş ve özel kesim.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 5940.0,
                            KategoriId = 5,
                            Resim = "marni-takim.webp",
                            UrunAdi = "Marni Kırmızı & Siyah Takım"
                        },
                        new
                        {
                            Id = 22,
                            Aciklama = "Hafif ve şık günlük elbise, sade tasarımıyla her ortama uygun.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 1650.0,
                            KategoriId = 5,
                            Resim = "pea-elbise.webp",
                            UrunAdi = "Pea Elbise"
                        },
                        new
                        {
                            Id = 23,
                            Aciklama = "Klasik siyah korse ve etek kombini — zarif ve feminen bir tarz.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 2640.0,
                            KategoriId = 5,
                            Resim = "siyah-korse-etek.webp",
                            UrunAdi = "Siyah Korse ve Etek"
                        },
                        new
                        {
                            Id = 24,
                            Aciklama = "Nike Air Jordan 1 ikonik kırmızı-siyah renk kombinasyonu, klasik basketbol siluet.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 4950.0,
                            KategoriId = 6,
                            Resim = "nike-air-jordan-1.webp",
                            UrunAdi = "Nike Air Jordan 1 Red & Black"
                        },
                        new
                        {
                            Id = 25,
                            Aciklama = "Puma Future Rider retro tasarım spor ayakkabı, hafif ve günlük konfor.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 2970.0,
                            KategoriId = 6,
                            Resim = "puma-future-rider.webp",
                            UrunAdi = "Puma Future Rider"
                        },
                        new
                        {
                            Id = 26,
                            Aciklama = "Off-white ve kırmızı renkli sneaker, modern siluet ve dayanıklı taban.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 3960.0,
                            KategoriId = 6,
                            Resim = "spor-ayakkabi-beyaz-kirmizi.webp",
                            UrunAdi = "Spor Ayakkabı Beyaz & Kırmızı"
                        },
                        new
                        {
                            Id = 27,
                            Aciklama = "Nike beyzbol ayakkabısı, sahada maksimum tutuş ve hareket kabiliyeti.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 2640.0,
                            KategoriId = 6,
                            Resim = "nike-baseball-cleats.webp",
                            UrunAdi = "Nike Baseball Cleats"
                        },
                        new
                        {
                            Id = 28,
                            Aciklama = "Off-white tonlarda spor ayakkabı, sokak modasına uygun şık tasarım.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 3630.0,
                            KategoriId = 6,
                            Resim = "spor-ayakkabi-off-white.webp",
                            UrunAdi = "Sports Sneakers Off White"
                        },
                        new
                        {
                            Id = 29,
                            Aciklama = "Longines Master Collection, İsviçre otomatik mekanizma ve klasik tasarım.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 49500.0,
                            KategoriId = 7,
                            Resim = "longines-master.webp",
                            UrunAdi = "Longines Master Collection"
                        },
                        new
                        {
                            Id = 30,
                            Aciklama = "Rolex Cellini Date, siyah kadran, otomatik mekanizma ve 18 ayar altın kasa.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 297000.0,
                            KategoriId = 7,
                            Resim = "rolex-cellini-date.webp",
                            UrunAdi = "Rolex Cellini Date Black"
                        },
                        new
                        {
                            Id = 31,
                            Aciklama = "Rolex Cellini Moonphase, ay safhası göstergesi ve premium İsviçre işçiliği.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 429000.0,
                            KategoriId = 7,
                            Resim = "rolex-cellini-moonphase.webp",
                            UrunAdi = "Rolex Cellini Moonphase"
                        },
                        new
                        {
                            Id = 32,
                            Aciklama = "Rolex Datejust, ikonik tasarım, otomatik mekanizma ve sürekli güncellenen tarih göstergesi.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 363000.0,
                            KategoriId = 7,
                            Resim = "rolex-datejust.webp",
                            UrunAdi = "Rolex Datejust"
                        },
                        new
                        {
                            Id = 33,
                            Aciklama = "Klasik tasarımlı kahverengi deri kayışlı kol saati, günlük şık kullanım.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 2970.0,
                            KategoriId = 7,
                            Resim = "kahverengi-deri-kayisli-saat.webp",
                            UrunAdi = "Kahverengi Deri Kayışlı Saat"
                        },
                        new
                        {
                            Id = 34,
                            Aciklama = "Chanel Coco Noir Eau de Parfum, gizemli ve oryantal kadın parfümü.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 4290.0,
                            KategoriId = 8,
                            Resim = "chanel-coco-noir.webp",
                            UrunAdi = "Chanel Coco Noir EDP"
                        },
                        new
                        {
                            Id = 35,
                            Aciklama = "Dior J'adore, çiçeksi ve feminen — klasik bir kadın parfümü.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 2970.0,
                            KategoriId = 8,
                            Resim = "dior-jadore.webp",
                            UrunAdi = "Dior J'adore EDP"
                        },
                        new
                        {
                            Id = 36,
                            Aciklama = "Gucci Bloom, beyaz çiçek kompozisyonu ile zarif kadın parfümü.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 2640.0,
                            KategoriId = 8,
                            Resim = "gucci-bloom.webp",
                            UrunAdi = "Gucci Bloom EDP"
                        },
                        new
                        {
                            Id = 37,
                            Aciklama = "Essence Lash Princess False Lash Effect maskara — yoğun ve uzun kirpik etkisi.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 330.0,
                            KategoriId = 8,
                            Resim = "essence-mascara.webp",
                            UrunAdi = "Essence Lash Princess Maskara"
                        },
                        new
                        {
                            Id = 38,
                            Aciklama = "Mat bitişli, uzun süre kalıcı klasik kırmızı ruj.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 429.0,
                            KategoriId = 8,
                            Resim = "kirmizi-ruj.webp",
                            UrunAdi = "Kırmızı Mat Ruj"
                        },
                        new
                        {
                            Id = 39,
                            Aciklama = "Prada deri kadın el çantası — lüks ve zarif tasarım.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 19800.0,
                            KategoriId = 9,
                            Resim = "prada-canta.webp",
                            UrunAdi = "Prada Kadın El Çantası"
                        },
                        new
                        {
                            Id = 40,
                            Aciklama = "Heshe markası gerçek deri kadın çanta, geniş hacim ve klasik tasarım.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 4290.0,
                            KategoriId = 9,
                            Resim = "heshe-deri-canta.webp",
                            UrunAdi = "Heshe Deri Kadın Çantası"
                        },
                        new
                        {
                            Id = 41,
                            Aciklama = "Mavi renk şık kadın el çantası — günlük ve özel etkinlikler için.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 1650.0,
                            KategoriId = 9,
                            Resim = "mavi-el-cantasi.webp",
                            UrunAdi = "Mavi Kadın El Çantası"
                        },
                        new
                        {
                            Id = 42,
                            Aciklama = "Klasik siyah çerçeveli güneş gözlüğü, UV400 koruma.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 990.0,
                            KategoriId = 9,
                            Resim = "siyah-gunes-gozlugu.webp",
                            UrunAdi = "Siyah Güneş Gözlüğü"
                        },
                        new
                        {
                            Id = 43,
                            Aciklama = "Yeşil ve siyah ton kombinli moda güneş gözlüğü — günlük şık aksesuar.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 1155.0,
                            KategoriId = 9,
                            Resim = "yesil-siyah-gozluk.webp",
                            UrunAdi = "Yeşil & Siyah Güneş Gözlüğü"
                        },
                        new
                        {
                            Id = 44,
                            Aciklama = "Annibale Colombo el yapımı çift kişilik yatak — İtalyan tasarımı ve premium malzeme.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 62700.0,
                            KategoriId = 10,
                            Resim = "annibale-colombo-yatak.webp",
                            UrunAdi = "Annibale Colombo Yatak"
                        },
                        new
                        {
                            Id = 45,
                            Aciklama = "Annibale Colombo lüks oturma grubu koltuk, hakiki deri kaplama.",
                            Aktif = true,
                            Anasayfa = true,
                            Fiyat = 82500.0,
                            KategoriId = 10,
                            Resim = "annibale-colombo-koltuk.webp",
                            UrunAdi = "Annibale Colombo Koltuk"
                        },
                        new
                        {
                            Id = 46,
                            Aciklama = "Knoll Saarinen Executive konferans sandalyesi, ikonik orta yüzyıl modern tasarım.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 16500.0,
                            KategoriId = 10,
                            Resim = "knoll-saarinen-sandalye.webp",
                            UrunAdi = "Knoll Saarinen Sandalye"
                        },
                        new
                        {
                            Id = 47,
                            Aciklama = "African Cherry ahşap komodin, sade ve sıcak detaylarla yatak odasına şıklık.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 9900.0,
                            KategoriId = 10,
                            Resim = "komodin-african-cherry.webp",
                            UrunAdi = "Komodin African Cherry"
                        },
                        new
                        {
                            Id = 48,
                            Aciklama = "Modern tasarım masa lambası — çalışma masası ve okuma köşeleri için ideal aydınlatma.",
                            Aktif = true,
                            Anasayfa = false,
                            Fiyat = 1650.0,
                            KategoriId = 10,
                            Resim = "masa-lambasi.webp",
                            UrunAdi = "Modern Masa Lambası"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("dotnet_store.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("dotnet_store.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("dotnet_store.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("dotnet_store.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_store.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("dotnet_store.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dotnet_store.Models.CartItem", b =>
                {
                    b.HasOne("dotnet_store.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_store.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("dotnet_store.Models.OrderItem", b =>
                {
                    b.HasOne("dotnet_store.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_store.Models.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("dotnet_store.Models.Urun", b =>
                {
                    b.HasOne("dotnet_store.Models.Kategori", "Kategori")
                        .WithMany("Uruns")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("dotnet_store.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("dotnet_store.Models.Kategori", b =>
                {
                    b.Navigation("Uruns");
                });

            modelBuilder.Entity("dotnet_store.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
